### ISSUE TITLE
Remove IDE specific files

### ISSUE THREAD

**Issue by ricardoboss** [CryptoKass/dilithium#1]
Hi!

I want to work in IntelliJ Community and would therefore like to remove all IDE specific files and ignore them with the `.gitignore`.

If desired, I would create a new branch with all IDE specific project files removed and added to the ignore file (including the IntelliJ Idea project files).

**Comment by CryptoKass** [comment]
Great idea, I *hopefully removed all IDE specific files and added them to `.gitignore`
